import { Get } from "../utils/index.d.ts";
import { Any, AnyType, ResolveAny } from "./any.d.ts";
import { Never, NeverType, ResolveNever } from "./never.d.ts";
import { Const, ConstType, ResolveConst } from "./const.d.ts";
import { Enum, EnumType, ResolveEnum } from "./enum.d.ts";
import { Primitive, PrimitiveType, ResolvePrimitive } from "./primitive.d.ts";
import { Arr, ArrType, ResolveArr } from "./array.d.ts";
import { Tuple, TupleType, ResolveTuple } from "./tuple.d.ts";
import { Object, ObjectType, ResolveObject } from "./object.d.ts";
import { Union, UnionType, ResolveUnion } from "./union.d.ts";
import { Intersection, IntersectionType, ResolveIntersection } from "./intersection/index.d.ts";
import { Error, ErrorType } from "./error.d.ts";
import { Exclusion, ExclusionType, ResolveExclusion } from "./exclusion/index.d.ts";
export declare type MetaType = AnyType | NeverType | ConstType | EnumType | PrimitiveType | ArrType | TupleType | ObjectType | UnionType | IntersectionType | ExclusionType | ErrorType;
export declare type Resolve<T, D = Exclude<T, undefined>> = {
    any: ResolveAny;
    never: ResolveNever;
    const: ResolveConst<D>;
    enum: ResolveEnum<D>;
    primitive: ResolvePrimitive<D>;
    array: ResolveArr<D>;
    tuple: ResolveTuple<D>;
    object: ResolveObject<D>;
    union: ResolveUnion<D>;
    intersection: ResolveIntersection<D>;
    exclusion: ResolveExclusion<D>;
    error: never;
}[Get<D, "type"> extends MetaType ? Get<D, "type"> : "error"];
export { Any, Never, Const, Enum, Primitive, Arr, Tuple, Object, Union, Intersection, Exclusion, Error, };
