import { Primitive, Any, Never } from "../meta-types/index.d.ts";
import { ParseConstSchema } from "./const.d.ts";
import { ParseEnumSchema } from "./enum.d.ts";
import { ParseMixedSchema } from "./mixed.d.ts";
import { ParseArrSchema } from "./array.d.ts";
import { ParseObjectSchema } from "./object.d.ts";
import { ParseAnyOfSchema } from "./anyOf.d.ts";
import { ParseOneOfSchema } from "./oneOf.d.ts";
import { ParseAllOfSchema } from "./allOf.d.ts";
import { ParseNotSchema } from "./not.d.ts";
import { ParseIfThenElseSchema } from "./ifThenElse.d.ts";
export declare type ParseSchema<S> = {
    any: Any;
    never: Never;
    null: Primitive<null>;
    boolean: Primitive<boolean>;
    number: Primitive<number>;
    string: Primitive<string>;
    mixed: ParseMixedSchema<S>;
    object: ParseObjectSchema<S>;
    array: ParseArrSchema<S>;
    const: ParseConstSchema<S>;
    enum: ParseEnumSchema<S>;
    anyOf: ParseAnyOfSchema<S>;
    oneOf: ParseOneOfSchema<S>;
    allOf: ParseAllOfSchema<S>;
    not: ParseNotSchema<S>;
    ifThenElse: ParseIfThenElseSchema<S>;
}[InferSchemaType<S>];
declare type InferSchemaType<S> = S extends true | string ? "any" : S extends false ? "never" : "if" extends keyof S ? "ifThenElse" : "not" extends keyof S ? "not" : "allOf" extends keyof S ? "allOf" : "oneOf" extends keyof S ? "oneOf" : "anyOf" extends keyof S ? "anyOf" : "enum" extends keyof S ? "enum" : "const" extends keyof S ? "const" : "type" extends keyof S ? S["type"] extends any[] ? "mixed" : S["type"] extends "null" ? "null" : S["type"] extends "boolean" ? "boolean" : S["type"] extends "integer" | "number" ? "number" : S["type"] extends "string" ? "string" : S["type"] extends "object" ? "object" : S["type"] extends "array" ? "array" : "never" : "any";
export {};
