import { Get } from "../../utils/index.d.ts";
import { MetaType, Never, Error } from "../index.d.ts";
import { Value } from "../primitive.d.ts";
import { IntersectConst } from "./const.d.ts";
import { IntersectEnum } from "./enum.d.ts";
import { IntersectExclusion } from "./exclusion.d.ts";
import { Intersect } from "./index.d.ts";
export declare type IntersectPrimitive<A, B> = {
    any: A;
    never: Never;
    const: IntersectConst<B, A>;
    enum: IntersectEnum<B, A>;
    primitive: Value<A> extends Value<B> ? A : Value<B> extends Value<A> ? B : Never;
    array: Never;
    tuple: Never;
    object: Never;
    union: Intersect<B, A>;
    intersection: Error<"Cannot intersect intersection">;
    exclusion: IntersectExclusion<B, A>;
    error: B;
    errorTypeProperty: Error<"Missing type property">;
}[Get<B, "type"> extends MetaType ? Get<B, "type"> : "errorTypeProperty"];
